In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('chennai_cars.xlsx')

In [3]:
df.columns

Index(['new_car_detail', 'new_car_overview', 'new_car_feature',
       'new_car_specs', 'car_links'],
      dtype='object')

In [4]:
import pandas as pd
import ast

# Sample data: assuming df is your DataFrame with a column 'new_car_detail'
data_list = df['new_car_detail'].to_list()

# Function to convert string to dictionary if necessary
def to_dict(data):
    if isinstance(data, str):
        try:
            return ast.literal_eval(data)
        except (ValueError, SyntaxError):
            return {}
    return data

# Function to flatten a single dictionary
def flatten_dict(data):
    if not isinstance(data, dict):
        return {}
    
    if 'trendingText' in data:
        # Flatten the nested dictionary
        flat_data = {
            **data,  # Unpack the main dictionary
            **{f'trendingText_{k}': v for k, v in data['trendingText'].items()}  # Flatten the nested dictionary
        }
        del flat_data['trendingText']  # Remove the original nested dictionary
    else:
        # If 'trendingText' key is missing, just return the data as is
        flat_data = data
    return flat_data

# Convert strings to dictionaries if needed
data_list = [to_dict(item) for item in data_list]

# Flatten all rows
flattened_data_list = [flatten_dict(row) for row in data_list]

# Convert to DataFrame
df_flattened = pd.DataFrame(flattened_data_list)

# Display the DataFrame
df_flattened

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText_imgUrl,trendingText_heading,trendingText_desc
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,8654,Turbo DCT Anniversary Edition,₹ 11.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,4025,7 Seater Standard BSIV,₹ 4.15 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
2,0,Petrol,SUV,"30,000",Manual,1,1st Owner,Nissan,Nissan Magnite,2021,8135,Turbo XV Premium BSVI,₹ 7.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
3,0,Petrol,Hatchback,"59,247",Manual,1,1st Owner,Hyundai,Hyundai i10,2015,1579,Sportz 1.1L,₹ 3.98 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
4,0,Petrol,Hatchback,"50,000",Manual,1,1st Owner,Honda,Honda Jazz,2015,1341,1.2 VX i VTEC,₹ 5.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1414,0,Petrol,Hatchback,"42,891",Automatic,1,1st Owner,Maruti,Maruti Swift,2018,6190,AMT VXI,₹ 6.20 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1415,0,Diesel,SUV,"59,100",Manual,1,1st Owner,Renault,Renault Duster,2018,5050,85PS Diesel RxZ,₹ 8.90 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1416,0,Petrol,SUV,"55,913",Automatic,1,1st Owner,Tata,Tata Nexon,2018,6364,1.2 Revotron XZA Plus,₹ 8.01 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1417,0,Diesel,SUV,"65,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Tiguan,2017,5849,2.0 TDI Highline,₹ 20.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1418,0,Diesel,Sedan,"60,000",Automatic,1,1st Owner,BMW,BMW 3 Series GT,2019,6630,Sport,₹ 35.75 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

In [5]:
data = df['new_car_overview'].to_list()
nested_dict_list_str= pd.DataFrame(data)

In [6]:
import pandas as pd
import ast

# Convert each string to a dictionary
nested_dict_list = [ast.literal_eval(d) for d in nested_dict_list_str[0]]

# Function to extract and flatten each dictionary
def extract_flatten_dict(nested_dict):
    if 'top' in nested_dict:
        top_data = nested_dict['top']
        df = pd.DataFrame(top_data)
        df = df.drop(columns=['icon'], errors='ignore')  # Drop the 'icon' column if present
        return df.set_index('key').T
    else:
        return pd.DataFrame()

# Extract and flatten all dictionaries
df_list = [extract_flatten_dict(d) for d in nested_dict_list]

# Concatenate all DataFrames into one
df_combined = pd.concat(df_list, ignore_index=True)

# Display the combined DataFrame
df_combined

key,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture
0,2022,Third Party insurance,Petrol,5 Seats,"20,000 Kms",TN02,First Owner,998 cc,Automatic,2022
1,Feb 2015,Comprehensive,Petrol,7 Seats,"20,687 Kms",TN04,First Owner,1196 cc,Manual,2015
2,2021,Third Party insurance,Petrol,5 Seats,"30,000 Kms",TN22,First Owner,999 cc,Manual,2021
3,May 2015,Comprehensive,Petrol,5 Seats,"59,247 Kms",TN11,First Owner,1086 cc,Manual,2015
4,2015,Third Party insurance,Petrol,5 Seats,"50,000 Kms",KA03,First Owner,1199 cc,Manual,2015
...,...,...,...,...,...,...,...,...,...,...
1414,Jun 2018,Third Party insurance,Petrol,5 Seats,"42,891 Kms",TN09,First Owner,1197 cc,Automatic,2018
1415,Feb 2019,Third Party insurance,Diesel,5 Seats,"59,100 Kms",TN11,First Owner,1461 cc,Manual,2018
1416,Aug 2018,Not Available,Petrol,5 Seats,"55,913 Kms",TN11,First Owner,1198 cc,Automatic,2018
1417,Aug 2017,Comprehensive,Diesel,5 Seats,"65,000 Kms",TN22,First Owner,1968 cc,Automatic,2017
1418,Oct 2019,Comprehensive,Diesel,5 Seats,"60,000 Kms",TN87,First Owner,1995 cc,Automatic,2019